Update update-embedded-player.yml

diff --git a/.github/workflows/update-embedded-player.yml b/.github/workflows/update-embedded-player.yml
--- a/.github/workflows/update-embedded-player.yml
+++ b/.github/workflows/update-embedded-player.yml
@@ -19,7 +19,7 @@ jobs:
         working-directory: ./embedded-player
         run: |
           OLD_EMBEDDED_PLAYER_VERSION=$(node -p "require('./package.json').dependencies['@antmedia/web_player']")
-          npm install --save @antmedia/web_player@latest
+          npm install --save @antmedia/web_player@latest || { echo 'npm install failed' ; exit 1; }
           NEW_EMBEDDED_PLAYER_VERSION=$(node -p "require('./package.json').dependencies['@antmedia/web_player']")
           echo "OLD_EMBEDDED_PLAYER_VERSION=$OLD_EMBEDDED_PLAYER_VERSION" >> $GITHUB_ENV
           echo "NEW_EMBEDDED_PLAYER_VERSION=$NEW_EMBEDDED_PLAYER_VERSION" >> $GITHUB_ENV
